# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f172ece7824047fa6524998651503ab71be3bccd25987c15990b23311fec2a4eb97e26c4eac599510a750ddee95e841fef1ce56cc4db35c36122d9da05dd76c0

test:
  secret_key_base: cf89d7376abfdbb6165183261fb404bc83bd453fc7834218f1a38f23a46cdcd636a7de25a60fafcb4a2072cf8614fd34e124ae289ab6cd936d4f57f1d0365e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
